version: '3.8'
services:
  client:
    container_name: react-coding-challenge
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:8080
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true